Med322a/Med322a/Controllers/CancelAppointmentController.cs
using Med322a.DataModels;
using Med322a.ViewModels;
using Med322a.Views.Models.Med322.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

namespace Med322a.Controllers
{
    public class CancelAppointmentController : Controller
    {
		private readonly string apiUrl;
		private readonly HttpClient httpClient = new HttpClient();
		private readonly int pageSize;

		public CancelAppointmentController(IConfiguration _config)
		{
			apiUrl = _config["ApiUrl"];
			pageSize = int.Parse(_config["PageSize"]);
		}

		public async Task<IActionResult> Index (VMPageParam vMPageParam)
        {
			ViewBag.biodataId = HttpContext.Session.GetString("userId") ?? String.Empty;
			ViewBag.userId = HttpContext.Session.GetString("userId") ?? String.Empty;
			long userId = long.Parse(HttpContext.Session.GetString("userId"));
			VMResponse? response = new VMResponse();
			VMResponse? appointmentResponse = new VMResponse();
			VMCombined? vMCombined = new VMCombined();
			VMMRole? userData = new VMMRole();

			try
			{
				//dptin userDatanya
				response = JsonConvert.DeserializeObject<VMResponse?>(
					await httpClient.GetStringAsync(apiUrl + "Patient/GetRoleByUserId/" + userId));
				if (response == null)
				{
					throw new ArgumentException($"No Patient with {userId} found!");
				}
				if (!response.success || response.data == null)
				{
					HttpContext.Session.SetString("errMsg", response.message);
					return RedirectToAction("Index", "Home");
				}
				else
				{
					userData = JsonConvert.DeserializeObject<VMMRole>(response.data.ToString());
					vMCombined.RoleModel = userData;
				}

				//dapatkan list appointmentnya
				if(vMPageParam.filter != null)
				{
					appointmentResponse = JsonConvert.DeserializeObject<VMResponse?>(
							await httpClient.GetStringAsync(apiUrl + "CancelAppointment/GetFilter/"
							+ vMPageParam.filter + "/" + userId));
				}
				else
				{
					appointmentResponse = JsonConvert.DeserializeObject<VMResponse?>(
							await httpClient.GetStringAsync(apiUrl + "CancelAppointment/" + userId));
				}

				if (appointmentResponse == null)
				{
					throw new ArgumentException($"No Appointment with {userId} found!");
				}
				if (!appointmentResponse.success || appointmentResponse.data == null)
				{
					HttpContext.Session.SetString("errMsg", appointmentResponse.message);
					return RedirectToAction("Index", "Home");
				}
				else
				{
					List<VMCancelAppointment> cancelAppointment = JsonConvert.DeserializeObject
						<List<VMCancelAppointment>>(appointmentResponse.data.ToString());
					vMCombined.CancelAppointment = cancelAppointment;
				}

				ViewBag.OrderID = string.IsNullOrEmpty(vMPageParam.orderby) ? "id_desc" : "";
				ViewBag.OrderName = (vMPageParam.orderby == "name") ? "name_desc" : "name";

				ViewBag.OrderBy = vMPageParam.orderby;
				ViewBag.Filter = vMPageParam.filter;
				ViewBag.UserRole = vMCombined.RoleModel;
				switch (vMPageParam.orderby)
				{
					case "name":
						vMCombined.CancelAppointment = vMCombined.CancelAppointment.OrderBy(product => product.Fullname).ToList();
						break;
					case "name_desc":
						vMCombined.CancelAppointment = vMCombined.CancelAppointment.OrderByDescending(product => product.Fullname).ToList();
						break;
					default:
						vMCombined.CancelAppointment = vMCombined.CancelAppointment.OrderBy(productdata => productdata.AppointmentId).ToList();
						break;
				}
			}
			catch (Exception ex)
			{
				HttpContext.Session.SetString("errMsg", ex.Message);
				return RedirectToAction("Index", "Home");
			}
			return View(PageView<VMCancelAppointment>.CreateAsync(vMCombined.CancelAppointment, vMPageParam.pageNumber ?? 1, pageSize));
		}

        public async Task<IActionResult> Edit(int id)
        {
            //VMCancelAppointment? apiTreatResponse = JsonConvert.DeserializeObject<VMCancelAppointment?>(await httpClient.GetStringAsync(apiUrl + "CancelAppointment/Get/" + id));
            //HttpContext.Session.SetString("DocID", apiTreatResponse.DoctorId.ToString() ?? "0");

            ////ViewBag.docId = int.Parse(HttpContext.Session.GetString("DocID"));
            List<VMDoctorTreatment> dataDT = new List<VMDoctorTreatment>();

            //VMDoctorTreatment? apiTreatNameResponse = new VMDoctorTreatment();
            try
            {

                VMResponse? apiResponse = JsonConvert.DeserializeObject<VMResponse?>(await httpClient.GetStringAsync(apiUrl + "CancelAppointment/GetAppointmentId/" + id));

                VMCancelAppointment? data = JsonConvert.DeserializeObject<VMCancelAppointment>(apiResponse.data.ToString());

                int x = (int)data.DoctorId;
                VMResponse? apiTreatNameResponse = JsonConvert.DeserializeObject<VMResponse?>(
					await httpClient.GetStringAsync(apiUrl + "DoctorTreatment/GetAllTreatment/" + x));

                dataDT = JsonConvert.DeserializeObject<List<VMDoctorTreatment>>(apiTreatNameResponse.data.ToString());


                //dataTreatment= JsonConvert.DeserializeObject<List<VMDoctorTreatment>>(apiTreatResponse.data.ToString());
                ViewBag.Treatment = JsonConvert.DeserializeObject<List<VMDoctorTreatment?>>(apiTreatNameResponse.data.ToString());


                //foreach (VMDoctorTreatment item in dataDT)
                //{
                //    if (data.DoctorTreatId == item.Id)
                //    {
                //        ViewBag.Treatment = item.Id;
                //    }
                //}

                return View(data);
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("errMsg", ex.Message);
                return View();
            }
        }

        public async Task<IActionResult> Delete(int Id)
        {
            VMResponse? apiResponse;
            apiResponse = JsonConvert.DeserializeObject<VMResponse>(await httpClient.GetStringAsync(apiUrl + "CancelAppointment/GetAppointmentId/" + Id));

            VMCancelAppointment relData = JsonConvert.DeserializeObject<VMCancelAppointment>(apiResponse.data.ToString());
            ViewBag.Title = "Batalkan Rencana Kedatangan";

            return View(relData);
        }

        [HttpPost]
        public async Task<VMResponse> Delete(VMCancelAppointment data)
        {
            VMResponse? apiResponse = new VMResponse();
            try
            {
                apiResponse = JsonConvert.DeserializeObject<VMResponse>(await (
                    await httpClient.DeleteAsync(apiUrl + "CancelAppointment/Delete/" + data.AppointmentId)).Content.ReadAsStringAsync());
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("errMsg", ex.Message);
            }
            HttpContext.Session.SetString("infoMsg", apiResponse.message);

            return apiResponse;
        }
    }
}

Med322a/Med322a/Views/CancelAppointment/Delete.cshtml
@using Med322a.ViewModels;
@model VMCancelAppointment
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<div class="card">
    <div class="card-header h3">@ViewBag.Title</div>
    <div class="card-body">
        Anda yakin akan membatalkan rencana kedatangan berikut ?
        <span><h4>@Model.Fullname</h4></span>
        <span><h5>@Model.AppDate?.ToString("d MMMM yyyy"), @Model.MedicFacility</h5></span>
        <span><h6>@Model.DoctorName - @Model.treatment</h6></span>
    </div>
    <div class="card-footer">
        <div class="d-flex justify-content-between">
            &nbsp;
            <form asp-action="Delete" method="post" id="frmDeletePatient">
                <input type="hidden" name="DeletedBy" value="@Model.userid" />
                <input type="hidden" name="AppointmentId" value="@Model.AppointmentId" />
                <input type="hidden" name="DeletedBy" value="@Model.userid" />
                <input type="hidden" name="CustomerId" value="@Model.customerId" />
                <input type="hidden" name="BiodataId" value="@Model.biodataId" />


                <div>
                    <button class="btn btn-sm btn-danger" type="submit"><i class="ti-trash"></i> Yes</button>
                    <button type="button" id="btnCancel" class="btn btn-sm btn-success"><i class="ti-close"></i> No</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $("#btnCancel").click(function () {
        $("#myModal").modal("hide")
    })
    $("#frmDeletePatient").validate({
        submitHandler: function (form) {
            debugger;
            if (confirm("Data will be delete..."))
                $.ajax({
                    url: "/CancelAppointment/Delete",
                    type: "post",
                    data: $(form).serialize(),
                    dataType: "json",
                    beforeSend: function () {
                        // Proses sebelum memanggil Controller
                    },
                    success: function (apiResponse) {
                        // Proses setelah Controller selesai
                        if (apiResponse.success) {
                            location.reload();
                        } else {
                            alert(apiResponse.message)
                        }
                    },
                    error: function (errResponse) {
                        // Proses ketika controller terjadi kesalahan
                        alert("Failed to proceed");

                    }
                });
            else
                return false;
        }
    });

Med322a/Med322a/Views/CancelAppointment/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
@model VMCancelAppointment

<form id="frmEditPatient" method="post" asp-action="Edit" asp-controller="CancelAppointment">
    <input type="hidden" name="ModifiedBy" value="@Model.userid" />
    <input type="hidden" name="CustomerId" value="@Model.customerId" />
    <input type="hidden" name="BiodataId" value="@Model.biodataId" />


    <div class="card">
        <div class="card-header h3">Dr. @Model.DoctorName</div>
        <div class="card-body">
            <div class="row">
                <label class="form-label">Konsultasi Untuk *</label>
                <select name="" disabled="true">
                    <option value="@Model.AppointmentId">@Model.Fullname, @Model.RelationName</option>
                </select>
            </div>
            <div class="row">
                <label class="form-label">Faskes *</label>
                <select name="" disabled="true">
                    <option value="@Model.MedicFacility">@Model.MedicFacility</option>
                </select>
            </div>
            <div class="row">

                <label class="form-label">Waktu Kedatangan</label>
                <input class="form-control" type="date" name="Dob" value="@Model.AppDate?.ToString("yyyy-MM-dd")" />
            </div>
            <div class="row">
                <label class="form-label">Tindakan Medis</label>
                <div class="form-group" disabled>
                    <select name="">

                        @foreach (VMDoctorTreatment item in ViewBag.Treatment)
                        {
                            if (item.Id == Model.doctortreatment)
                            {
                                <option value="@item.Id" selected>@item.Name</option>
                            }
                            else
                            {

                                <option value="@item.Id">@item.Name</option>
                            }
                        }
                    </select>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between">
                &nbsp;
            </div>
            <button type="submit" class="btn btn-sm btn-success"><i class="ti-save"></i> Save</button>
            <button type="button" id="btnCancel" class="btn btn-sm btn-success"><i class="ti-close"></i> Cancel</button>
        </div>
    </div>
</form>
<script>
    $("#btnCancel").click(function () {
        $("#myModal").modal("hide")
    })

        //$("#frmEditPatient").validate({
        //    rules: {
        //        Fullname: {
        //            minlength: 3,
        //            maxlength: 50,
        //            required: true
        //        },
        //        Dob: {
        //            required: true,
        //            date: true,
        //            maxDate: true // Menggunakan aturan maxDate yang baru kita definisikan
        //        },
        //    },
        //    errorClass: "text-danger"
        //});

        //$(document).ready(function () {
        //    // Validasi formulir menggunakan jQuery Validate
        //    $("#frmEditPatient").validate();

        //    // Mengirimkan formulir melalui Ajax saat disubmit
        //    $("#frmEditPatient").submit(function (event) {
        //        event.preventDefault(); // Mencegah pengiriman formulir default

        //        if ($("#frmEditPatient").valid()) {
        //            // Mengambil data formulir
        //            var formData = new FormData($(this)[0]);

        //            // Mengirim data melalui Ajax
        //            $.ajax({
        //                url: '/CancelAppointment/Edit/', // Ubah sesuai dengan URL endpoint Add di Controller Anda
        //                type: 'POST',
        //                data: formData,
        //                processData: false, // Tidak memproses data secara otomatis
        //                contentType: false, // Tidak mengatur tipe konten secara otomatis
        //                success: function (apiResponse) {
        //                    if (apiResponse.success) {
        //                        // Redirect ke halaman yang sesuai setelah berhasil menambahkan data
        //                        window.location.href = '@Url.Action("Index")'; // Ubah sesuai dengan URL yang benar
        //                    } else {
        //                        // Tampilkan pesan kesalahan jika ada
        //                        alert(apiResponse.message);
        //                    }
        //                },
        //                error: function (errResponse) {
        //                    alert("Submit Failed");
        //                }
        //            });
        //        }
        //    });
        //});
</script>

Med322a/Med322a/Views/CancelAppointment/Index.cshtml
@using Med322a.ViewModels
@using Med322a.Views.Models.Med322.Models;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model PageView<VMCancelAppointment>
<main class="content">
	<div class="container-fluid p-0">
		<div class="row">
			<div class="col-md-4 col-xl-3 d-flex align-items-stretch">
				<div class="row ">
					<div class="col-xl-12 align-self-start">
						<div class="card mb-3 ">
							<div class="card-header">
								<h5 class="card-title mb-0">Profile Detail </h5>
							</div>
							<div class="card-body">
								<div class="d-flex justify-content-between">
									&nbsp; <h5><i id="editImages" class="bi-pencil-square" type="button"></i></h5>
								</div>
								<div class="text-center">
									<img id="myImage" src="~/images/@(ViewBag.UserRole.ImagePath??"logo.png")" alt="~/images/logo.png" class="img-fluid rounded-circle mb-2" width="128" height="128">

								</div>
								<h5 id="userName" class="card-title mb-0 text-center">@ViewBag.UserRole.Fullname</h5>
								<div id="userJobClass" class="text-muted mb-2 text-center">@ViewBag.UserRole.Name</div>
							</div>
						</div>

					</div>
					<div class="col-xl-12 align-self-end">
						<div class="mb-4">
							<div>
								<ul class="list-unstyled mb-0">
									<li class="mb-1"><a asp-action="" asp-controller="">Profile @ViewBag.UserRole.Fullname</a></li>
									<li class="mb-1"><a href="#">Pembelian Obat</a></li>
									<li class="mb-1"><a href="#">Rencana Kedatangan</a></li>
									<li class="mb-1"><a href="#">Riwayat Chat Dokter</a></li>
								</ul>
							</div>

						</div>

					</div>
				</div>
			</div>
			<div class="col-md-8 col-xl-9">
				<div class="card">
					<div class="card-header" id="contentViewIndex">
						<form id="frmFindData" asp-action="Index" asp-controller="CancelAppointment">
							<input type="hidden" name="orderby" value="@ViewBag.OrderBy" />
							<div class="d-flex justify-content-between mb-3">
								<button id="btnAdd" type="button" class="btn btn-success btn-sm"><i class="bi-plus-lg"></i></button>
								<button id="btnDeleteSelected" type="button" class="btn btn-danger btn-sm"><i class="bi-trash"></i> Cancel Selected Appointment</button>
								<div class="input-group w-50">
									<input id="txtFilter" name="Filter" placeholder="Find..." class="form-control" value="@ViewBag.Filter" />
									<button id="btnFilter" type="submit" class="btn btn-sm btn-primary"><i class="bi-search"></i></button>
								</div>
							</div>
						</form>
						<table class="table table-striped table-bordered">
							<thead>
								<tr>
									@*<th class="col-1"><a asp-action="ViewDataRelation" asp-route-filter="@ViewBag.Filter" asp-controller="Admin" asp-route-orderby="@ViewBag.OrderID">ID</a></th>*@
									<th class="col-1"><a asp-action="ViewDataRelation" asp-route-filter="" asp-controller="Admin" asp-route-orderby="">*</a></th>
									<th class="col-3"><a asp-action="Index" asp-route-filter="@ViewBag.Filter" asp-controller="CancelAppointment" asp-route-orderby="">Name</a></th>
									<th class="col-2">Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach (VMCancelAppointment data in Model)
								{
									<tr>
										<td><input type="checkbox" class="checkbox-delete" data-multipledelete="@data.customerId" /></td>
										<td>
											<h4>@data.Fullname</h4>
											<span><h5>@data.AppDate?.ToString("d MMMM yyyy"), @data.MedicFacility</h5></span>
											<span><h6>@data.DoctorName - @data.treatment</h6></span>
										</td>
										<td>
											@*<button data-cusrelid="@data.Id" class="btn btnDetails btn-sm btn-info btn-icon" title="Details..."><i class="ti-info"></i></button>*@
											<button data-customermemberid="@data.AppointmentId" class="btn btnEdit btn-sm btn-success btn-icon" title="Edit..."><i class="bi-pencil-square"></i> Ubah</button>
											<button data-customermemberid="@data.AppointmentId" class="btn btnDelete btn-sm btn-danger btn-icon" title="Delete..."><i class="bi-x"></i> Batalkan</button>
										</td>
									</tr>
								}
							</tbody>
							<tfoot>
								<tr>
									<td colspan="7" class="text-center">
										<div class="btn-group btn-rounded">
											<a asp-action="Index" asp-controller="CancelAppointment" title="Previous Page..." class="btn btn-primary btn-circle @(Model.PageIndex < 2? "disabled" : "")"
											   asp-route-filter="@ViewBag.Filter"
											   asp-route-orderby="@ViewBag.OrderBy"
											   asp-route-pageNumber="@(Model.PageIndex <= 1? Model.PageIndex : Model.PageIndex-1)">
												<i class="bi-skip-backward-fill"></i>
											</a>
											<span class="input-group-text">page @Model.PageIndex of @Model.TotalPages</span>
											<a asp-action="Index" asp-controller="CancelAppointment" title="Next Page..." class="btn btn-primary btn-circle @(Model.PageIndex >= Model.TotalPages? "disabled" : "")"
											   asp-route-filter="@ViewBag.Filter"
											   asp-route-orderby="@ViewBag.OrderBy"
											   asp-route-pageNumber="@(Model.PageIndex == Model.TotalPages ? Model.PageIndex : Model.PageIndex+1)">
												<i class="bi-skip-forward-fill"></i>
											</a>
										</div>
									</td>
								</tr>
							</tfoot>

						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>


<script>
	$(document).ready(function () {
		let userId = Number(@ViewBag.userId)
		let biodataId = Number(@ViewBag.biodataId)

		$("#btnFilter").click(function () {
			debugger
			$("#frmFindData").submit();
		});

		$("#editImages").click(function () {
			$("#myModalBody").load("/Patient/EditImages/" + userId)
			$("#myModal").modal("show")
		});

		$(".btnEdit").click(function () {
			let customermemberid = $(this).data("customermemberid");
			$("#myModalBody").load("/CancelAppointment/Edit/" + customermemberid);
			$("#myModal").modal("show");
		})

		$(".btnDelete").click(function () {
			let customermemberid = $(this).data("customermemberid");
			$("#myModalBody").load("/CancelAppointment/Delete/" + customermemberid);
			$("#myModal").modal("show");
		});
	});
</script>