Med322a/Med322a/Controllers/PatientController.cs
using Med322a.ViewModels;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using System.Globalization;
using System.Net.Http;
using System.Text;
using Med322a.DataAccess;
using Med322a.DataModels;

namespace Med322a.Controllers
{
	public class PatientController : Controller
	{
        private readonly string apiUrl;
        private readonly HttpClient client = new HttpClient();
        private readonly string imgFolder;
        private readonly IWebHostEnvironment env;

        public PatientController(IConfiguration configuration, IWebHostEnvironment env)
        {
            apiUrl = configuration["ApiUrl"];
            imgFolder = configuration["ImageFolder"];
            this.env = env;
        }

        private void DeleteOldImage(string oldImageFileName)
        {
            try
            {
                string uploadFolder = env.WebRootPath + "\\" + imgFolder + "\\" + oldImageFileName;

                if (System.IO.File.Exists(uploadFolder))
                {
                    System.IO.File.Delete(uploadFolder);
                }
                //else
                //{
                //    throw new Exception("File Doesn't Exist!");
                //}
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("errMsg", ex.Message);
            }
        }

        public string UploadFile(IFormFile file)
        {
            string uniquefileName = string.Empty;

            if (file != null)
            {
                //Generate unique ID for filename
                uniquefileName = Guid.NewGuid().ToString() + "-" + file.FileName;
                //where to save the image ? worry not.. here is the place
                string uploadFolder = env.WebRootPath + "\\" + imgFolder + "\\" + uniquefileName;

                //uploading
                using (FileStream fileStream = new FileStream(uploadFolder, FileMode.CreateNew))
                {
                    file.CopyTo(fileStream);
                }
            }

            return uniquefileName;
        }

        public IActionResult Index()
		{
			return View();
		}

		public async Task <IActionResult> ProfileTab(long id)
        {
            ViewBag.userId = HttpContext.Session.GetString("userId") ?? String.Empty;
            VMResponse response = new VMResponse();
			VMMUser? userData = new VMMUser();

			try
			{
                response = JsonConvert.DeserializeObject<VMResponse?>(
					await client.GetStringAsync(apiUrl + "Patient/Get/" + id));
                if (response == null)
                {
                    throw new ArgumentException($"No Patient with {id} found!");
                }
                if (!response.success || response.data == null)
                {
                    HttpContext.Session.SetString("errMsg", response.message);
                }
                else
                {
                    HttpContext.Session.SetString("infoMsg", $"Patient data with id = {id} successfully fetched!");
                    userData = JsonConvert.DeserializeObject<VMMUser>(response.data.ToString());
                }
            }
            catch (Exception ex)
			{
                HttpContext.Session.SetString("errMsg", ex.Message);
            }
            return View(userData);
		}

        public async Task<IActionResult> Edit(long id)
        {
            ViewBag.userId = HttpContext.Session.GetString("userId") ?? String.Empty;
            VMResponse response = new VMResponse();
            VMMUser? userData = new VMMUser();

            try
            {
                response = JsonConvert.DeserializeObject<VMResponse?>(
                    await client.GetStringAsync(apiUrl + "Patient/Get/" + id));
                if (response == null)
                {
                    throw new ArgumentException($"No Patient with {id} found!");
                }
                if (!response.success || response.data == null)
                {
                    HttpContext.Session.SetString("errMsg", response.message);
                }
                else
                {
                    HttpContext.Session.SetString("infoMsg", $"Patient data with id = {id} successfully fetched!");
                    userData = JsonConvert.DeserializeObject<VMMUser>(response.data.ToString());
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("errMsg", ex.Message);
            }
            return View(userData);
        }

        [HttpPost]
        public async Task<VMResponse?> Edit(VMMUser user)
        {
            VMResponse? apiResponse;
            try
            {
                // Convert Form Data to Json
                string jsonData = JsonConvert.SerializeObject(user);

                // Wrapping JSon inside an HTML Body to be send as HTTP Put Request method 
                HttpContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                // Process updated Product via API
                apiResponse = JsonConvert.DeserializeObject<VMResponse?>(
                    await (await client.PutAsync($"{apiUrl}Patient/Edit", content)).Content.ReadAsStringAsync()
                );

                // Check API Connection
                if (apiResponse == null)
                {
                    throw new ArgumentException("No Connection to Product API!");
                }

                // Check API Response
                if (!apiResponse.success || apiResponse.data == null)
                    throw new ArgumentException(apiResponse.message);
            }
            catch (Exception ex)
            {
                apiResponse = new VMResponse();
                apiResponse.success = false;
                apiResponse.message = ex.Message;

                HttpContext.Session.SetString("errMsg", ex.Message);
            }

            return apiResponse;

        }

        public async Task<IActionResult> EditEmailUser(long id)
        {
            ViewBag.userId = HttpContext.Session.GetString("userId") ?? String.Empty;
            VMResponse response = new VMResponse();
            VMMUser? userData = new VMMUser();

            try
            {
                response = JsonConvert.DeserializeObject<VMResponse?>(
                    await client.GetStringAsync(apiUrl + "Patient/Get/" + id));
                if (response == null)
                {
                    throw new ArgumentException($"No Patient with {id} found!");
                }
                if (!response.success || response.data == null)
                {
                    HttpContext.Session.SetString("errMsg", response.message);
                }
                else
                {
                    HttpContext.Session.SetString("infoMsg", $"Patient data with id = {id} successfully fetched!");
                    userData = JsonConvert.DeserializeObject<VMMUser>(response.data.ToString());
                }
			}
            catch (Exception ex)
            {
                HttpContext.Session.SetString("errMsg", ex.Message);
            }
            return View(userData);
        }

        [HttpPost]
        public JsonResult ValidateEmail(string email)
        {
            using (var dbContext = new DB_MEDContext()) // Inisialisasi konteks basis data
            {
                bool isEmailExists = dbContext.MUsers.Any(user => user.Email == email);
                return Json(new { exists = isEmailExists });
            }
        }

        [HttpPost]
        public async Task<VMResponse?> EditEmailUser (VMMUser user)
        {
            VMResponse? apiResponse;
            try
            {
                // Convert Form Data to Json
                string jsonData = JsonConvert.SerializeObject(user);

                // Wrapping JSon inside an HTML Body to be send as HTTP Put Request method 
                HttpContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                // Process updated Product via API
                apiResponse = JsonConvert.DeserializeObject<VMResponse?>(
                    await (await client.PutAsync($"{apiUrl}Patient/EditEmailUser", content)).Content.ReadAsStringAsync()
                );

                // Check API Connection
                if (apiResponse == null)
                {
                    throw new ArgumentException("No Connection to Product API!");
                }

                // Check API Response
                if (!apiResponse.success || apiResponse.data == null)
                    throw new ArgumentException(apiResponse.message);
            }
            catch (Exception ex)
            {
                apiResponse = new VMResponse();
                apiResponse.success = false;
                apiResponse.message = ex.Message;

                HttpContext.Session.SetString("errMsg", ex.Message);
            }

            return apiResponse;
        }

        public async Task<IActionResult> EditPasswordUser(int id)
        {
            ViewBag.userId = HttpContext.Session.GetString("userId") ?? String.Empty;
            
            return View(id);
        }

        [HttpPost]
        public async Task<VMResponse?> EditNewPasswordUser(VMMUser user)
        {
            VMResponse? apiResponse;
            try
            {
                // Convert Form Data to Json
                string jsonData = JsonConvert.SerializeObject(user);

                // Wrapping JSon inside an HTML Body to be send as HTTP Put Request method 
                HttpContent content = new StringContent(jsonData, Encoding.UTF8, "application/json");

                // Process updated Product via API
                apiResponse = JsonConvert.DeserializeObject<VMResponse?>(

Med322a/Med322a/Views/Shared/_AdminProfileSharedLayout.cshtml
<!--
	README for id name.
	img id="imgNavbar"
	img id="myImage"
	h5  id="userName"
	div id="userJobClass"
	
	Dibawah ini nav-tab pada profile layout
	id nav-tabnya sendiri = myTab

-->

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="img/icons/icon-48x48.png" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<!-- Bootstrap JS -->
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

	<link href="~/adminkit/static/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
</head>
    <body>
	<main class="content">
		<div class="container-fluid p-0">
			<div class="row">
				<div class="col-md-4 col-xl-3">
					<div class="card mb-3">
						<div class="card-header">
							<h5 class="card-title mb-0">Profile Details </h5>
						</div>
						<div class="card-body align">
							<div>
								<i data-feather="edit-2"></i>
							</div>
							<div class="text-center">
								<img id="myImage" src="~/images/logo.png" alt="~/images/logo.png" class="img-fluid rounded-circle mb-2" width="128" height="128">

							</div>
							<h5  id="userName" class="card-title mb-0">Christina Mason</h5>
							<div id="userJobClass" class="text-muted mb-2">Lead Developer</div>
						</div>
						<hr class="my-0">
						
						<div class="card-body">
							<h5 class="h6 card-title">Menu</h5>
							<ul class="list-unstyled mb-0">
								<li class="mb-1"><a href="#">Pasien</a></li>
								<li class="mb-1"><a href="#">Pembelian Obat</a></li>
								<li class="mb-1"><a href="#">Rencana Kedatangan</a></li>
								<li class="mb-1"><a href="#">Riwayat Chat Dokter</a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-md-8 col-xl-9">
					<div class="card">
						<div class="card-header py-1">
							<!-- Nav tabs -->
							<ul class="nav nav-tabs" id="myTab" role="tablist">
								<li class="nav-item" role="presentation">
									<button class="nav-link active" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="true">Profile</button>
								</li>
								<li class="nav-item" role="presentation">
									<button class="nav-link" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="false">Alamat</button>
								</li>
								<li class="nav-item" role="presentation">
									<button class="nav-link" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings" type="button" role="tab" aria-controls="settings" aria-selected="false">Pembayaran</button>
								</li>
								<li class="nav-item" role="presentation">
									<button class="nav-link" id="messages-tab" data-bs-toggle="tab" data-bs-target="#messages" type="button" role="tab" aria-controls="messages" aria-selected="false">Messages</button>
								</li>
							</ul>
						</div>
						<div class="card-body py-2" id="tabsForProfileSharedLayout">
							<!-- Tab panes -->
							<div class="tab-content" id="tab-content">
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>
</body>
</html>

<!-- Tambahkan tautan ke Bootstrap JavaScript di sini -->
<script>
	$(document).ready(function () {
		// Fungsi untuk menampilkan konten sesuai dengan tab yang aktif
		function showTabContent(tabId, content) {
			if ($("#" + tabId).attr("aria-selected") === "true") {
				$("#tab-content").load(content);
			}	
		}
		// Tampilkan konten berdasarkan tab aktif saat halaman dimuat
		showTabContent("profile-tab", "/Patient/Privacy/");
		showTabContent("home-tab", "ini profile");
		showTabContent("messages-tab", "ini Content");
		showTabContent("settings-tab", "ini Setting");

		// Tambahkan event listener untuk setiap tombol tab
		$("#home-tab").click(function () {
			$("#tab-content").load("/Patient/Index/");
		});
		$("#profile-tab").click(function () {
			$("#tab-content").load("/Patient/Privacy/");
		});
		$("#messages-tab").click(function () {
			$("#tab-content").text("user id sekarang adalah : " + @ViewBag.UserRoleId);
		});
		$("#settings-tab").click(function () {
			$("#tab-content").text("ini Setting");
		});
	});
</script>

Med322a/Med322a/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Med322a</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Med322a.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Med322a</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Med322a - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Med322a/Med322a/Views/Shared/_Layoutadminkit.cshtml
@{
	ViewBag.UserRoleId = Context.Session.GetString("userRoleId") ?? String.Empty;

}
<!DOCTYPE html>
<html lang="en">
	@*cek push dari reza prihandi*@
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="~/images/MED-logo.png" />

	<link rel="canonical" href="https://demo-basic.adminkit.io/" />

	<title>AdminKit Demo - Bootstrap 5 Admin Template</title>

	<!-- JQuery JS -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
	@*<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>*@
	
</head>

<body>

	<div class="wrapper">
		@if (!string.IsNullOrEmpty(ViewBag.UserRoleId))
		{
			<partial name="_Sidebar" />
		}

		<div class="main">
			<partial name="_Topbar" />

			<main class="content">
				<partial name="_Session" />
				<div class="container-fluid p-0">
					@RenderBody()
				</div>
			</main>

			<footer class="footer" style="background-color:#01579b;">
				<div class="container-fluid">
					<div class="row text-white">
						<div class="col-6 text-start">
							<p class="mb-0">
								<a class="text-white" href="https://adminkit.io/" target="_blank"><strong>Med.ID</strong></a> &copy;
							</p>
						</div>
						<div class="col-6 text-end">
							<ul class="list-inline">
								<li class="list-inline-item">
									<a class="text-white" href="https://adminkit.io/" target="_blank">Support</a>
								</li>
								<li class="list-inline-item">
									<a class="text-white" href="https://adminkit.io/" target="_blank">Help Center</a>
								</li>
								<li class="list-inline-item">
									<a class="text-white" asp-controller="Home" asp-action="Privacy" target="_blank">Privacy</a>
								</li>
								<li class="list-inline-item">
									<a class="text-white" href="https://adminkit.io/" target="_blank">Terms</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>
	<partial name="_Modal" />

	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

	<!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

	<link href="~/adminkit/static/css/app.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">

	<!-- Bootstrap JS -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

	@*<script src="~/adminkit/static/js/app.js"></script>*@

</body>

</html>

Med322a/Med322a/Views/Shared/_Session.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //Get Messages from Session
    ViewBag.InfoMsg = Context.Session.GetString("infoMsg")?? String.Empty;
    ViewBag.WarnMsg = Context.Session.GetString("warnMsg")?? String.Empty;
    ViewBag.ErrMsg = Context.Session.GetString("errMsg")?? String.Empty;

    ViewBag.UserRoleId = Context.Session.GetString("userRoleId")?? String.Empty;
    ViewBag.UserId = Context.Session.GetString("userId")?? String.Empty;
    ViewBag.UserFullName = Context.Session.GetString("userFullName")?? String.Empty;
    ViewBag.email = Context.Session.GetString("email")?? String.Empty;
    ViewBag.password = Context.Session.GetString("password")?? String.Empty;

    //Reset Messages Session
    Context.Session.SetString("infoMsg", String.Empty);
    Context.Session.SetString("warnMsg", String.Empty);
    Context.Session.SetString("errMsg", String.Empty);

    //Context.Session.SetString("userRoleId", String.Empty);
}

<div id="alertPlaceholder" class="alert alert-dismissible m-auto p-0" role="alert" aria-hidden="true">
    @*Isi dari alert*@
</div>


<script>
    $(document).ready(function(){
        function alertPopUp(msg, type){
            $("#alertPlaceholder").append(
                '<div class= "alert alert-' + type + ' d-flex justify-content-between">'
                + '<div>' + msg + '</div>'
                + '<button type="button" class="btn btn-sm btn-close" data-bs-dismiss="alert" aria-label="Close">'
                + '</button>'
                + '</div>'
            );
        }

        if ("@ViewBag.InfoMsg" != "") alertPopUp("@Html.Raw(ViewBag.InfoMsg)", 'info');
        if ("@ViewBag.WarnMsg" != "") alertPopUp("@Html.Raw(ViewBag.WarnMsg)", 'warning');
        if ("@ViewBag.ErrMsg" != "") alertPopUp("@Html.Raw(ViewBag.ErrMsg)", 'danger');
    });
</script>

Med322a/Med322a/Views/Shared/_Sidebar.cshtml
@using Newtonsoft.Json
@*@model List<VMMenuForView>*@
@*
    Tes Git Tambahan
	For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	//ViewBag.UserId = Context.Session.GetString("userId") ?? String.Empty;
}

<nav id="sidebar" class="sidebar js-sidebar">
	<div class="sidebar-content js-simplebar">
		<a class="sidebar-brand" asp-controller="Home" asp-action="Index">
			<span class="align-middle">Med.ID</span>
		</a>

		<ul class="sidebar-nav">
			<li class="sidebar-header">
				Pages
			</li>
			@*Isi menu awal atau Default sebelum login*@
			<li class="sidebar-item active">
				<a class="sidebar-link" asp-controller="Home" asp-action="Index">
					<i class="bi-house"></i> <span class="align-middle">Dashboard</span>
				</a>
			</li>

			<li class="sidebar-item">
				<a id="linkSearchDoctor" class="sidebar-link">
					<i class="bi bi-search"></i> <span class="align-middle">Search Doctor</span>
				</a>
			</li>
			
			<li class="sidebar-item">
				<a class="sidebar-link" asp-controller="Home" asp-action="Logout">
					<i class="bi-door-open"></i> <span class="align-middle">Keluar</span>
				</a>
			</li>

			@if(ViewBag.UserRoleId == "1"){
				<li class="sidebar-header">Admin</li>
			}
			else if(ViewBag.UserRoleId == "2"){
				<li class="sidebar-header">Pasien</li>
			}
			else if(ViewBag.UserRoleId == "3"){
				<li class="sidebar-header">Dokter</li>
			}
			@*Isi Menu setelah Login, pemanggilan dari database m_menu*@
			@if (Context.Session.GetString("MenuForView") is string serializedMenuData){
				var menuForView = JsonConvert.DeserializeObject<List<VMMenuForView>>(serializedMenuData);
				@foreach (var menu in menuForView)
				{
					@*Penentuan menu berdasarakan rolenya sebagain apa*@
					if(menu.RoleId.ToString() == ViewBag.UserRoleId)
					{
						<li class="sidebar-item">
							<a class="sidebar-link" href="javascript:void(0);" onclick="redirectToRelativeUrl('@menu.Url')" > 
								<i class="@menu.SmallIcon"></i><span class="align-middle">@menu.Name</span>
							</a>
						</li>
					}
				}
			}
			@if(ViewBag.UserRoleId == "1"){
				<li class="sidebar-item align-middle dropdown">
					<button class="sidebar-link btn btn-secondary dropdown-toggle" type="button" id="dropdownPengaturan" data-bs-toggle="dropdown" aria-expanded="false">
						Pengaturan
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownPengaturan">
						<li><a class="dropdown-item" asp-controller="AturAkses" asp-action="IndexAtur">Atur Akses</a></li>
					</ul>
				</li>
			}
		</ul>
	</div>
</nav>
<script>
    function redirectToRelativeUrl(targetUrl) {
        var currentUrl = window.location.href;
        var parts = currentUrl.split("/");
        var baseUrl = parts[0];

        window.location.href = baseUrl + '/' + targetUrl;
    }
</script>

<script>
	$(document).ready(function () {
		$("#linkSearchDoctor").click(function () {
			$("#myModalBody").load("/Doctor/SearchDoctor");
			$("#myModal").modal("show");
		});
	});
</script>

@{
	//if(ViewBag.UserRoleId == "1"){
	//	<li class="sidebar-header">
	//		Admin
	//	</li>
	//	//asp-controller="Bank" asp-action="Index"
	//	<li class="sidebar-item">
 //           <a class="sidebar-link" href="~/Bank/Index" > 
	//			<i class="bi bi-bank"></i><span class="align-middle">Bank</span>
 //           </a>
 //       </li>
	//	<li class="sidebar-item">
	//		<a class="sidebar-link" asp-controller="Doctor" asp-action="Specialization">
	//			<i class="align-middle" data-feather="book"></i> <span class="align-middle">Doctor Specialization</span>
	//		</a>
	//	</li>

	//	<li class="sidebar-item">
	//		<a class="sidebar-link" asp-controller="Payment" asp-action="Index">
	//			<i class="bi bi-credit-card"></i><span class="align-middle">Payment</span>
	//		</a>
	//	</li>

	//	<li class="sidebar-item">
	//		<a class="sidebar-link" asp-controller="Akses" asp-action="Index">
	//			<i class="bi bi-book"></i><span class="align-middle">Hak Akses</span>
	//		</a>
	//	</li>
	//	<li class="sidebar-item align-middle dropdown">
	//		<button class="sidebar-link btn btn-secondary dropdown-toggle" type="button" id="dropdownPengaturan" data-bs-toggle="dropdown" aria-expanded="false">
	//			Pengaturan
	//		</button>
	//		<ul class="dropdown-menu" aria-labelledby="dropdownPengaturan">
	//			<li><a class="dropdown-item" asp-controller="AturAkses" asp-action="IndexAtur">Atur Akses</a></li>
	//		</ul>
	//	</li>
	
	//}
	//else if (ViewBag.UserRoleId == "2")
	//{
	//	@*Pembeda*@

	//	<li class="sidebar-header">
	//		Pasien
	//	</li>

	//	<li class="sidebar-item">
	//		<a class="sidebar-link" asp-controller="Patient" asp-action="SearchDoctor">
	//			<i class="align-middle" data-feather="bar-chart-2"></i> <span class="align-middle">Cari Dokter</span>
	//		</a>
	//	</li>

	//	<li class="sidebar-item">
	//		<a class="sidebar-link" href="maps-google.html">
	//			<i class="align-middle" data-feather="map"></i> <span class="align-middle">Maps</span>
	//		</a>
	//	</li>
	//}
	//else if (ViewBag.UserRoleId == "3")
	//{
	//	<li class="sidebar-header">
	//		Dokter
	//	</li>

	//	<li class="sidebar-item">
	//		<a class="sidebar-link" asp-controller="Doctor" asp-action="Profile">
	//			<i class="align-middle bi bi-pencil-fill"></i> <span class="align-middle">Profile</span>
	//		</a>
	//	</li>

	//	<li class="sidebar-item">
	//		<a class="sidebar-link" href="maps-google.html">
	//			<i class="align-middle" data-feather="map"></i> <span class="align-middle">Maps</span>
	//		</a>
	//	</li>
	//}
}